services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    env_file:
      - .env.production
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    container_name: gitwatch-postgres
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
      - "-c"
      - "log_min_duration_statement=0"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_line_prefix=%t [%p]: user=%u,db=%d,app=%a "
    volumes:
      - ./pgdata:/var/lib/postgresql
    ports:
      - "${DB_PORT}:5432"
    networks:
        - gitwatch-net
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "gitwatch-app"
    env_file:
      - .env.production
    environment:
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - /app/node_modules
    networks:
        - gitwatch-net
    healthcheck:
      test: ["CMD","curl","-f" , "http://localhost:${PORT}/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env.production
    volumes:
    - pgadmin_data:/var/lib/pgadmin
    container_name: gitwatch-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_HOST_PORT}:${PGADMIN_CONTAINER_PORT}"
    depends_on:
      - db
    networks:
      - gitwatch-net

  redis:
    image: "redis:alpine"
    container_name: gitwatch-redis
    env_file:
      - .env.production
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: always
    networks:
      - gitwatch-net
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  gitwatch-net:
    driver: bridge

volumes:
  pgadmin_data: