/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type PrStatus = "CLOSED" | "MERGED" | "OPEN";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "COLLABORATOR" | "OWNER" | "VIEWER";

export interface CommitFiles {
  additions: Generated<number | null>;
  changes: Generated<number | null>;
  commit_id: number;
  created_at: Generated<Timestamp | null>;
  deletions: Generated<number | null>;
  filename: string;
  id: Generated<number>;
  status: string | null;
  updated_at: Generated<Timestamp | null>;
}

export interface Commits {
  analyzed_at: Timestamp | null;
  author_email: string | null;
  author_name: string | null;
  branch: string | null;
  committed_at: Timestamp | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  message: string | null;
  pull_request_id: number | null;
  repository_id: number;
  sha: string;
  updated_at: Generated<Timestamp | null>;
}

export interface EmailVerificationTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<number>;
  token_hash: string;
  user_id: number;
}

export interface PullRequests {
  author_email: string | null;
  base_sha: string | null;
  created_at: Generated<Timestamp | null>;
  head_sha: string | null;
  id: Generated<number>;
  pr_number: number;
  provider_id: number | null;
  repository_id: number;
  status: PrStatus | null;
  title: string | null;
  updated_at: Generated<Timestamp | null>;
}

export interface RefreshTokens {
  created_at: Generated<Timestamp>;
  device_id: string | null;
  expires_at: Timestamp;
  id: Generated<number>;
  ip_address: string | null;
  revoked_at: Timestamp | null;
  token_hash: string;
  user_id: number;
}

export interface Repositories {
  created_at: Generated<Timestamp | null>;
  default_branch: Generated<string | null>;
  id: Generated<number>;
  is_active: Generated<boolean | null>;
  name: string;
  owner_id: number | null;
  provider_repo_id: string | null;
  updated_at: Generated<Timestamp | null>;
}

export interface RepoUser {
  created_at: Generated<Timestamp | null>;
  repository_id: number;
  role: UserRole | null;
  updated_at: Generated<Timestamp | null>;
  user_id: number;
}

export interface Users {
  avatar_url: string | null;
  created_at: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  is_active: Generated<boolean>;
  password: string;
  username: string;
}

export interface DB {
  commit_files: CommitFiles;
  commits: Commits;
  email_verification_tokens: EmailVerificationTokens;
  pull_requests: PullRequests;
  refresh_tokens: RefreshTokens;
  repo_user: RepoUser;
  repositories: Repositories;
  users: Users;
}
